version: '3'

services: 
# ganache:
#    image: trufflesuite/ganache-cli:latest
#    container_name: "ganache"
#    tty: true
#    ports:
#      - 8545:8545

  truffle:
    # build: .
    image: roten_truffle #local image
    container_name: "truffle"
    tty: true
    volumes: 
      - ./src:/root/src
    working_dir: "/root/src"
